<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Devtap:: Developer Template Assistance Program</title>
        <link rel="stylesheet" type="text/css" href="css/devtapstyle.css">
	<script src="js/jquery-2.0.3.min.js"></script>
        
    </head>
    <body>
        <div class="devtap_container">
            <header>
                <a href="#"><div id="logo"><span class="logostyle">Devtap</span><br><span class="logo-details">Developers Template Assistance Program</span></div></a>
            </header>
            <article>
                <b>Hey!!</b><br><br>Thanks for using Devtap (Developers Template Assistance Program). This is a open source program that helps you generate a W3C compliance HTMl5 / CSS3 based web page skeleton. You can choose your required header, nav, body and footer layouts by just clicking on the option and the program will automatically generate W3C valid XHTML code with CSS 2,3. <br>You will hence be able to create any PSD design into standard code HTMl 5 /CSS 3 page in practically few less than 10 minutes and all you need to do is to color and add up the respective images inside the div and other tags already generated by the Devtap. <br><h3>WOW! is n't it Amazing....</h3> <br>Let's get cracking... Shall We ???? :)
            </article>
            <a href="choice.php">
            <div id="banner">                
             </div>
             </a>
        </div>
    </body>
</html>
